apiVersion: v1
kind: ConfigMap
metadata:
  name: projet-devops-config
  namespace: {{ .Values.namespace }}
data:
  {{- range $key, $value := .Values.configMap }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
