apiVersion: v1
kind: PersistentVolume
metadata:
  name: open-webui-pv
spec:
  capacity:
    storage: {{ .Values.openwebui.storage }}
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: {{ .Values.openwebui.hostPath }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open-webui-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  volumeName: open-webui-pv
  resources:
    requests:
      storage: {{ .Values.openwebui.storage }}
