apiVersion: v1
kind: Service
metadata:
  name: ollama-service
  namespace: {{ .Values.namespace }}
  labels:
    app: ollama
spec:
  selector:
    app: ollama
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.ollama.containerPort }}
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: open-webui-service
  namespace: {{ .Values.namespace }}
  labels:
    app: open-webui
spec:
  selector:
    app: open-webui
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.openwebui.containerPort }}
  type: ClusterIP
