apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open-webui-pvc
  namespace: projet-devops

spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: manual
  volumeName: open-webui-pv

  resources:
    requests:
      storage: 5Gi