apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

labels:
  - pairs:
      environment: development
    includeSelectors: true

patches:
  - target:
      kind: Deployment
      name: ollama
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "4Gi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "2"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "1Gi"
  - target:
      kind: HorizontalPodAutoscaler
      name: open-webui-hpa
    patch: |-
      - op: replace
        path: /spec/maxReplicas
        value: 1