apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

labels:
  - pairs:
      environment: production
    includeSelectors: true

patches:
  - target:
      kind: Deployment
      name: ollama
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "10Gi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "4Gi"
  - target:
      kind: HorizontalPodAutoscaler
      name: open-webui-hpa
    patch: |-
      - op: replace
        path: /spec/maxReplicas
        value: 5
  - target:
      kind: Deployment
      name: open-webui
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Always