apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-pvc
  namespace: projet-devops

spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: manual
  volumeName: ollama-pv

  resources:
    requests:
      storage: 5Gi